# Copyright 2018-2022 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that provides the Open Liberty and WebSphere Liberty runtimes."
  homepage = "https://github.com/paketo-buildpacks/liberty"
  id = "paketo-buildpacks/liberty"
  keywords = ["java", "javaee", "liberty"]
  name = "Paketo Buildpack for Liberty"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/liberty/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "bin/build", "bin/detect", "bin/main", "bin/helper", "buildpack.toml", "templates/server.tmpl", "templates/app.tmpl", "templates/features.tmpl", "templates/expose-default-endpoint.xml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "the application server to use"
    name = "BP_JAVA_APP_SERVER"

  [[metadata.configurations]]
    build = true
    default = "ol"
    description = "Install type of Liberty"
    launch = false
    name = "BP_LIBERTY_INSTALL_TYPE"

  [[metadata.configurations]]
    build = true
    default = "*"
    description = "Which version of the Liberty runtime to install"
    launch = false
    name = "BP_LIBERTY_VERSION"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "The Liberty profile to install"
    launch = false
    name = "BP_LIBERTY_PROFILE"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "Name of the server to use"
    launch = true
    name = "BP_LIBERTY_SERVER_NAME"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "Context root to use for app"
    launch = false
    name = "BP_LIBERTY_CONTEXT_ROOT"

  [[metadata.configurations]]
    build = false
    default = ""
    description = "Sets the logging level"
    launch = true
    name = "BPL_LIBERTY_LOG_LEVEL"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "A space separated list of liberty features to install."
    launch = false
    name = "BP_LIBERTY_FEATURES"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "Disable running the feature installer."
    launch = false
    name = "BP_LIBERTY_FEATURE_INSTALL_DISABLED"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "OpenJ9 only: Disable building the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_DISABLED"

  [[metadata.configurations]]
    build = true
    default = "100"
    description = "OpenJ9 only: Size to use for the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_SIZE_MB"

  [[metadata.configurations]]
    build = true
    default = "1"
    description = "OpenJ9 only: Number of iterations to cycle the server when building the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_NUM_ITERATIONS"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "OpenJ9 only: Disable trimming the size of the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_TRIM_SIZE_DISABLED"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.4:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-full"
    name = "Open Liberty (All Features)"
    purl = "pkg:maven/io.openliberty/openliberty-runtime@23.0.0.4"
    sha256 = "4c67071fe383ca64e8d71172fe8695d7152152d5c05b28aaf1b98b53cbface5f"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-runtime/23.0.0.4/openliberty-runtime-23.0.0.4.zip"
    version = "23.0.4"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.4:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-jakartaee10"
    name = "Open Liberty (Jakarta EE10)"
    purl = "pkg:maven/io.openliberty/openliberty-jakartaee10@23.0.0.4"
    sha256 = "3a883af3da97de2c2166aed95750b58c6ac635abb20983017dd38e2aa910c91d"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-jakartaee10/23.0.0.4/openliberty-jakartaee10-23.0.0.4.zip"
    version = "23.0.4"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.3:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-javaee8"
    name = "Open Liberty (Java EE8)"
    purl = "pkg:maven/io.openliberty/openliberty-javaee8@23.0.0.3"
    sha256 = "1200cc429976e6a39e25397b9b8ceb16aa5a7f764550f24df3bc6b407c909847"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-javaee8/23.0.0.3/openliberty-javaee8-23.0.0.3.zip"
    version = "23.0.3"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.3:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-webProfile10"
    name = "Open Liberty (Web Profile 10)"
    purl = "pkg:maven/io.openliberty/openliberty-webProfile10@23.0.0.3"
    sha256 = "0acda0432dcf6c0ea162579a62902b9de441e3493bcf781acdf1a9120e99a02a"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-webProfile10/23.0.0.3/openliberty-webProfile10-23.0.0.3.zip"
    version = "23.0.3"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.4:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-webProfile8"
    name = "Open Liberty (Web Profile 8)"
    purl = "pkg:maven/io.openliberty/openliberty-webProfile8@23.0.0.4"
    sha256 = "38b731d6170f584e3dd46215ac50e87ac5351b202e4fd53680b2cb43135b76ab"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-webProfile8/23.0.0.4/openliberty-webProfile8-23.0.0.4.zip"
    version = "23.0.4"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.4:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-microProfile6"
    name = "Open Liberty (Micro Profile 6)"
    purl = "pkg:maven/io.openliberty/openliberty-microProfile6@23.0.0.4"
    sha256 = "5835a5691a273f58f316e538811f3ef1d0ef5c425e2006ce382e51f7a97822bf"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-microProfile6/23.0.0.4/openliberty-microProfile6-23.0.0.4.zip"
    version = "23.0.4"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.4:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-microProfile4"
    name = "Open Liberty (Micro Profile 4)"
    purl = "pkg:maven/io.openliberty/openliberty-microProfile4@23.0.0.4"
    sha256 = "bcf93041df46d8fec56a5a8445fa80c756970e17787a00a07cba10228769cc80"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-microProfile4/23.0.0.4/openliberty-microProfile4-23.0.0.4.zip"
    version = "23.0.4"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.4:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-kernel"
    name = "Open Liberty (Kernel)"
    purl = "pkg:maven/io.openliberty/openliberty-kernel@23.0.0.4"
    sha256 = "0def9e84e25064003c63dfd4c91e52766ea6986dfe7069cccda40a8a02a5780f"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-kernel/23.0.0.4/openliberty-kernel-23.0.0.4.zip"
    version = "23.0.4"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:23.0.0.4:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-kernel"
    name = "WebSphere Liberty (Kernel)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-kernel@23.0.0.4"
    sha256 = "cff7ec6189cb3983ab164576a9fc19cff15fbfa7b707c54a0936f80fc8ba93b1"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-kernel/23.0.0.4/wlp-kernel-23.0.0.4.zip"
    version = "23.0.4"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:23.0.0.4:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-jakartaee10"
    name = "WebSphere Liberty (Jakarta EE9)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-jakartaee10@23.0.0.4"
    sha256 = "a7df9af6a24215e90c582eef2ec9b12bc305f98dd63a8f925b2e1ef675956360"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-jakartaee10/23.0.0.4/wlp-jakartaee10-23.0.0.4.zip"
    version = "23.0.4"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:23.0.0.4:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-javaee8"
    name = "WebSphere Liberty (Java EE8)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-javaee8@23.0.0.4"
    sha256 = "e9984ce3fa8d0422f58352213f8dcfa88dac0f412a5ccb4b5c6b7be3dc67dd82"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-javaee8/23.0.0.4/wlp-javaee8-23.0.0.4.zip"
    version = "23.0.4"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:23.0.0.4:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-javaee7"
    name = "WebSphere Liberty (Java EE7)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-javaee7@23.0.0.4"
    sha256 = "a00e343bfefa5aeab4b61874ef5ad7c44c0243205139a7b27e77bf9b8c1dbc96"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-javaee7/23.0.0.4/wlp-javaee7-23.0.0.4.zip"
    version = "23.0.4"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:23.0.0.4:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-webProfile10"
    name = "WebSphere Liberty (Web Profile 10)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-webProfile10@23.0.0.4"
    sha256 = "caa04e76af6f44b2943a5d15178e6b07416ec9adfbd5ea5f95404eae74e9954c"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-webProfile10/23.0.0.4/wlp-webProfile10-23.0.0.4.zip"
    version = "23.0.4"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:23.0.0.4:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-webProfile8"
    name = "WebSphere Liberty (Web Profile 8)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-webProfile8@23.0.0.4"
    sha256 = "4a7d6367f437dc9120d26a5381d83e7b5bf429aa1b06281b40049301f7d2aad7"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-webProfile8/23.0.0.4/wlp-webProfile8-23.0.0.4.zip"
    version = "23.0.4"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:23.0.0.3:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-webProfile7"
    name = "WebSphere Liberty (Web Profile 7)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-webProfile7@23.0.0.3"
    sha256 = "688fcf1f5ef25b443ab916bdaf22a0bbae96f617baebc3b420e8cfcbf4513274"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-webProfile7/23.0.0.3/wlp-webProfile7-23.0.0.3.zip"
    version = "23.0.3"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "*"
