# Copyright 2018-2023 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that provides the Open Liberty and WebSphere Liberty runtimes."
  homepage = "https://github.com/paketo-buildpacks/liberty"
  id = "paketo-buildpacks/liberty"
  keywords = ["java", "javaee", "liberty"]
  name = "Paketo Buildpack for Liberty"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/liberty/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "bin/build", "bin/detect", "bin/main", "bin/helper", "buildpack.toml", "templates/server.tmpl", "templates/app.tmpl", "templates/features.tmpl", "templates/expose-default-endpoint.xml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "the application server to use"
    name = "BP_JAVA_APP_SERVER"

  [[metadata.configurations]]
    build = true
    default = "ol"
    description = "Install type of Liberty"
    launch = false
    name = "BP_LIBERTY_INSTALL_TYPE"

  [[metadata.configurations]]
    build = true
    default = "*"
    description = "Which version of the Liberty runtime to install"
    launch = false
    name = "BP_LIBERTY_VERSION"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "The Liberty profile to install"
    launch = false
    name = "BP_LIBERTY_PROFILE"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "Name of the server to use"
    launch = true
    name = "BP_LIBERTY_SERVER_NAME"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "Context root to use for app"
    launch = false
    name = "BP_LIBERTY_CONTEXT_ROOT"

  [[metadata.configurations]]
    build = false
    default = ""
    description = "Sets the logging level"
    launch = true
    name = "BPL_LIBERTY_LOG_LEVEL"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "A space separated list of liberty features to install."
    launch = false
    name = "BP_LIBERTY_FEATURES"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "Disable running the feature installer."
    launch = false
    name = "BP_LIBERTY_FEATURE_INSTALL_DISABLED"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "OpenJ9 only: Disable building the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_DISABLED"

  [[metadata.configurations]]
    build = true
    default = "100"
    description = "OpenJ9 only: Size to use for the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_SIZE_MB"

  [[metadata.configurations]]
    build = true
    default = "1"
    description = "OpenJ9 only: Number of iterations to cycle the server when building the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_NUM_ITERATIONS"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "OpenJ9 only: Disable trimming the size of the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_TRIM_SIZE_DISABLED"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.10:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-full"
    name = "Open Liberty (All Features)"
    purl = "pkg:maven/io.openliberty/openliberty-runtime@23.0.0.10"
    sha256 = "31600732e6c39129cd033a54060e6f4a215e11de5fe26d14fed4edd3329955ea"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-23.0.0.10.tar.gz"
    source-sha256 = "43b87c72d3901a0ce172c7c3ac6e9e08f9bfcb5dffe6a0bcae4425d07f676b68"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-runtime/23.0.0.10/openliberty-runtime-23.0.0.10.zip"
    version = "23.0.10"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.10:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-jakartaee10"
    name = "Open Liberty (Jakarta EE10)"
    purl = "pkg:maven/io.openliberty/openliberty-jakartaee10@23.0.0.10"
    sha256 = "63e378865513b16e12b59f6a3f567063caae21e2bb3c016acb88af317de9f562"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-23.0.0.10.tar.gz"
    source-sha256 = "43b87c72d3901a0ce172c7c3ac6e9e08f9bfcb5dffe6a0bcae4425d07f676b68"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-jakartaee10/23.0.0.10/openliberty-jakartaee10-23.0.0.10.zip"
    version = "23.0.10"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.10:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-javaee8"
    name = "Open Liberty (Java EE8)"
    purl = "pkg:maven/io.openliberty/openliberty-javaee8@23.0.0.10"
    sha256 = "1a2bbd6d9e071b681d097bc93104cfe4082183e4f46767b8736d69e43d8522c9"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-23.0.0.10.tar.gz"
    source-sha256 = "43b87c72d3901a0ce172c7c3ac6e9e08f9bfcb5dffe6a0bcae4425d07f676b68"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-javaee8/23.0.0.10/openliberty-javaee8-23.0.0.10.zip"
    version = "23.0.10"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.10:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-webProfile10"
    name = "Open Liberty (Web Profile 10)"
    purl = "pkg:maven/io.openliberty/openliberty-webProfile10@23.0.0.10"
    sha256 = "37f7f067beef49cc9423e813b2a496565ffedcf5fcb1e68730fb35fd630eac48"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-23.0.0.10.tar.gz"
    source-sha256 = "43b87c72d3901a0ce172c7c3ac6e9e08f9bfcb5dffe6a0bcae4425d07f676b68"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-webProfile10/23.0.0.10/openliberty-webProfile10-23.0.0.10.zip"
    version = "23.0.10"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.10:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-webProfile8"
    name = "Open Liberty (Web Profile 8)"
    purl = "pkg:maven/io.openliberty/openliberty-webProfile8@23.0.0.10"
    sha256 = "7ee32560455bd786ba75ce9b7379e6a3de236d5cd5f12c50d0c8832c31c3162e"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-23.0.0.10.tar.gz"
    source-sha256 = "43b87c72d3901a0ce172c7c3ac6e9e08f9bfcb5dffe6a0bcae4425d07f676b68"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-webProfile8/23.0.0.10/openliberty-webProfile8-23.0.0.10.zip"
    version = "23.0.10"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.10:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-microProfile6"
    name = "Open Liberty (Micro Profile 6)"
    purl = "pkg:maven/io.openliberty/openliberty-microProfile6@23.0.0.10"
    sha256 = "37a3c3da74db75fb2912dd7d5f1a2bcd521e7251162a5a55abde2308baac3b31"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-23.0.0.10.tar.gz"
    source-sha256 = "43b87c72d3901a0ce172c7c3ac6e9e08f9bfcb5dffe6a0bcae4425d07f676b68"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-microProfile6/23.0.0.10/openliberty-microProfile6-23.0.0.10.zip"
    version = "23.0.10"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.10:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-microProfile4"
    name = "Open Liberty (Micro Profile 4)"
    purl = "pkg:maven/io.openliberty/openliberty-microProfile4@23.0.0.10"
    sha256 = "ae5789b56d0b5103ccef8160ef4e7a22182ce1d5bbd5813896ba8d57330bdabf"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-23.0.0.10.tar.gz"
    source-sha256 = "43b87c72d3901a0ce172c7c3ac6e9e08f9bfcb5dffe6a0bcae4425d07f676b68"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-microProfile4/23.0.0.10/openliberty-microProfile4-23.0.0.10.zip"
    version = "23.0.10"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.10:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-kernel"
    name = "Open Liberty (Kernel)"
    purl = "pkg:maven/io.openliberty/openliberty-kernel@23.0.0.10"
    sha256 = "441ec2aa5344510a9cf52c5055c706e3a75d4a98296b5ede1e3a86908bb81f1a"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-23.0.0.10.tar.gz"
    source-sha256 = "43b87c72d3901a0ce172c7c3ac6e9e08f9bfcb5dffe6a0bcae4425d07f676b68"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-kernel/23.0.0.10/openliberty-kernel-23.0.0.10.zip"
    version = "23.0.10"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:23.0.0.10:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-kernel"
    name = "WebSphere Liberty (Kernel)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-kernel@23.0.0.10"
    sha256 = "236b41a20bd3120dd318757d0fa5a04c233f220ff319b785e187556652bda3ac"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-kernel/23.0.0.10/wlp-kernel-23.0.0.10.zip"
    version = "23.0.10"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:23.0.0.10:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-jakartaee10"
    name = "WebSphere Liberty (Jakarta EE9)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-jakartaee10@23.0.0.10"
    sha256 = "1e7c5ef57b7b385f1c2d0b033c7132d3525398d0dee2f73846228ac2d78d5bd6"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-jakartaee10/23.0.0.10/wlp-jakartaee10-23.0.0.10.zip"
    version = "23.0.10"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:23.0.0.11:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-javaee8"
    name = "WebSphere Liberty (Java EE8)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-javaee8@23.0.0.11"
    sha256 = "c6fb63715a856cbf581d9100fac2de16b1338a4bb2cc2a56fd9fa01d45bbb9eb"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-javaee8/23.0.0.11/wlp-javaee8-23.0.0.11.zip"
    version = "23.0.11"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:23.0.0.10:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-javaee7"
    name = "WebSphere Liberty (Java EE7)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-javaee7@23.0.0.10"
    sha256 = "6ea014eaec16574dfd92b8d1b19cfe17de4218d6c46e71d677daacda3c808440"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-javaee7/23.0.0.10/wlp-javaee7-23.0.0.10.zip"
    version = "23.0.10"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:23.0.0.10:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-webProfile10"
    name = "WebSphere Liberty (Web Profile 10)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-webProfile10@23.0.0.10"
    sha256 = "6170c06061e3b0c1316cda625193010dfd792c76e7ad6fa43c8d277bb9f0fba2"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-webProfile10/23.0.0.10/wlp-webProfile10-23.0.0.10.zip"
    version = "23.0.10"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:23.0.0.10:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-webProfile8"
    name = "WebSphere Liberty (Web Profile 8)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-webProfile8@23.0.0.10"
    sha256 = "4354c087a0795f40924444ac6b41963cccd465eda4ad6fe5116023f46749c7e4"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-webProfile8/23.0.0.10/wlp-webProfile8-23.0.0.10.zip"
    version = "23.0.10"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:23.0.0.10:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-webProfile7"
    name = "WebSphere Liberty (Web Profile 7)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-webProfile7@23.0.0.10"
    sha256 = "9d02f6b596e7db294978f365ef7a2febd0a641b2eb0f0babdc8812844f0d18d9"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-webProfile7/23.0.0.10/wlp-webProfile7-23.0.0.10.zip"
    version = "23.0.10"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

[[stacks]]
  id = "*"
