# Copyright 2018-2023 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that provides the Open Liberty and WebSphere Liberty runtimes."
  homepage = "https://github.com/paketo-buildpacks/liberty"
  id = "paketo-buildpacks/liberty"
  keywords = ["java", "javaee", "liberty"]
  name = "Paketo Buildpack for Liberty"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/liberty/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "bin/build", "bin/detect", "bin/main", "bin/helper", "buildpack.toml", "templates/server.tmpl", "templates/app.tmpl", "templates/features.tmpl", "templates/expose-default-endpoint.xml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "the application server to use"
    name = "BP_JAVA_APP_SERVER"

  [[metadata.configurations]]
    build = true
    default = "ol"
    description = "Install type of Liberty"
    launch = false
    name = "BP_LIBERTY_INSTALL_TYPE"

  [[metadata.configurations]]
    build = true
    default = "*"
    description = "Which version of the Liberty runtime to install"
    launch = false
    name = "BP_LIBERTY_VERSION"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "The Liberty profile to install"
    launch = false
    name = "BP_LIBERTY_PROFILE"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "Name of the server to use"
    launch = true
    name = "BP_LIBERTY_SERVER_NAME"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "Context root to use for app"
    launch = false
    name = "BP_LIBERTY_CONTEXT_ROOT"

  [[metadata.configurations]]
    build = false
    default = ""
    description = "Sets the logging level"
    launch = true
    name = "BPL_LIBERTY_LOG_LEVEL"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "A space separated list of liberty features to install."
    launch = false
    name = "BP_LIBERTY_FEATURES"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "Disable running the feature installer."
    launch = false
    name = "BP_LIBERTY_FEATURE_INSTALL_DISABLED"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "OpenJ9 only: Disable building the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_DISABLED"

  [[metadata.configurations]]
    build = true
    default = "100"
    description = "OpenJ9 only: Size to use for the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_SIZE_MB"

  [[metadata.configurations]]
    build = true
    default = "1"
    description = "OpenJ9 only: Number of iterations to cycle the server when building the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_NUM_ITERATIONS"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "OpenJ9 only: Disable trimming the size of the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_TRIM_SIZE_DISABLED"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.7:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-full"
    name = "Open Liberty (All Features)"
    purl = "pkg:maven/io.openliberty/openliberty-runtime@23.0.0.7"
    sha256 = "a4fd7dfdee39b73bc4212e7353e4adfc09afc80a87c166427e0bb2877abef287"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-runtime/23.0.0.7/openliberty-runtime-23.0.0.7.zip"
    version = "23.0.7"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.8:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-jakartaee10"
    name = "Open Liberty (Jakarta EE10)"
    purl = "pkg:maven/io.openliberty/openliberty-jakartaee10@23.0.0.8"
    sha256 = "d92f753cc489573ab73597d5fc6b866ebc94a573036865760c230819235418fe"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-jakartaee10/23.0.0.8/openliberty-jakartaee10-23.0.0.8.zip"
    version = "23.0.8"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.7:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-javaee8"
    name = "Open Liberty (Java EE8)"
    purl = "pkg:maven/io.openliberty/openliberty-javaee8@23.0.0.7"
    sha256 = "5449e0367b24e018571b20610233cac9a79761c25bee89f0b9a3cbd1fa74c230"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-javaee8/23.0.0.7/openliberty-javaee8-23.0.0.7.zip"
    version = "23.0.7"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.7:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-webProfile10"
    name = "Open Liberty (Web Profile 10)"
    purl = "pkg:maven/io.openliberty/openliberty-webProfile10@23.0.0.7"
    sha256 = "12acc52652a06c1741b74fd3cdefe9d98a612b6d29f07b686375b4b741b55502"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-webProfile10/23.0.0.7/openliberty-webProfile10-23.0.0.7.zip"
    version = "23.0.7"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.7:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-webProfile8"
    name = "Open Liberty (Web Profile 8)"
    purl = "pkg:maven/io.openliberty/openliberty-webProfile8@23.0.0.7"
    sha256 = "77688128decc9acdc5effa3f35e39b71c3aa56c87b395597071c80ba50e30435"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-webProfile8/23.0.0.7/openliberty-webProfile8-23.0.0.7.zip"
    version = "23.0.7"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.8:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-microProfile6"
    name = "Open Liberty (Micro Profile 6)"
    purl = "pkg:maven/io.openliberty/openliberty-microProfile6@23.0.0.8"
    sha256 = "e64163cd103742b50e0857cdb99d6bbec0f556eaefcf4d8af8e3af1711f3920b"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-microProfile6/23.0.0.8/openliberty-microProfile6-23.0.0.8.zip"
    version = "23.0.8"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.8:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-microProfile4"
    name = "Open Liberty (Micro Profile 4)"
    purl = "pkg:maven/io.openliberty/openliberty-microProfile4@23.0.0.8"
    sha256 = "0a1dc86420a43d28633409fa31206c56960f922c22d882659d30dfcf46ea526e"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-microProfile4/23.0.0.8/openliberty-microProfile4-23.0.0.8.zip"
    version = "23.0.8"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:23.0.0.8:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-kernel"
    name = "Open Liberty (Kernel)"
    purl = "pkg:maven/io.openliberty/openliberty-kernel@23.0.0.8"
    sha256 = "cf0a03a75076abe1db03bd2486b41c21715c6aba1a164e0c8346224de2fc1757"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-kernel/23.0.0.8/openliberty-kernel-23.0.0.8.zip"
    version = "23.0.8"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:23.0.0.8:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-kernel"
    name = "WebSphere Liberty (Kernel)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-kernel@23.0.0.8"
    sha256 = "328f155249824c79859e92b8a1b510af051123fd3fabcebc8b1ae4f098be7c88"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-kernel/23.0.0.8/wlp-kernel-23.0.0.8.zip"
    version = "23.0.8"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:23.0.0.8:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-jakartaee10"
    name = "WebSphere Liberty (Jakarta EE9)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-jakartaee10@23.0.0.8"
    sha256 = "c342fcadba121f3b728b1a0db7afd01cec92e5157bbbd00952ff6d07ce1848b1"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-jakartaee10/23.0.0.8/wlp-jakartaee10-23.0.0.8.zip"
    version = "23.0.8"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:23.0.0.8:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-javaee8"
    name = "WebSphere Liberty (Java EE8)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-javaee8@23.0.0.8"
    sha256 = "7d8894ebc8c5bd64e3032238ecf8c41ccc43d45322b4407ba9a171107f9cc256"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-javaee8/23.0.0.8/wlp-javaee8-23.0.0.8.zip"
    version = "23.0.8"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:23.0.0.8:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-javaee7"
    name = "WebSphere Liberty (Java EE7)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-javaee7@23.0.0.8"
    sha256 = "6b324f78b96bd957e9932f810ef9020c98cd9fda2c667ac0b63c4ca751f9cf3b"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-javaee7/23.0.0.8/wlp-javaee7-23.0.0.8.zip"
    version = "23.0.8"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:23.0.0.8:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-webProfile10"
    name = "WebSphere Liberty (Web Profile 10)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-webProfile10@23.0.0.8"
    sha256 = "7eaba5b2044763111fec6126ed0398a0724f44a82766cf171e02ae3db42d23eb"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-webProfile10/23.0.0.8/wlp-webProfile10-23.0.0.8.zip"
    version = "23.0.8"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:23.0.0.7:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-webProfile8"
    name = "WebSphere Liberty (Web Profile 8)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-webProfile8@23.0.0.7"
    sha256 = "c6922412a394b5a03394d24c4b83aca88ce470fa7d73568f8b5e1e1317a3ede6"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-webProfile8/23.0.0.7/wlp-webProfile8-23.0.0.7.zip"
    version = "23.0.7"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:23.0.0.7:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-webProfile7"
    name = "WebSphere Liberty (Web Profile 7)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-webProfile7@23.0.0.7"
    sha256 = "74d9c846b2611bd3cc7cc3ef34e95c1e302c7c9048cd4432893cb6c069212ebe"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-webProfile7/23.0.0.7/wlp-webProfile7-23.0.0.7.zip"
    version = "23.0.7"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

[[stacks]]
  id = "*"
